// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD9M0KZpKzlGSfyQdzk8mU_CnxDJq3RWY',
    appId: '1:139054927656:web:bf388a4e42d4a711c74a1d',
    messagingSenderId: '139054927656',
    projectId: 'muzic-16d63',
    authDomain: 'muzic-16d63.firebaseapp.com',
    storageBucket: 'muzic-16d63.appspot.com',
    measurementId: 'G-B5WM25N396',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKwkZ_UnsQAN8gVyIQ3A7bzl6bzXdy7o4',
    appId: '1:139054927656:android:113f6c1630b165eac74a1d',
    messagingSenderId: '139054927656',
    projectId: 'muzic-16d63',
    storageBucket: 'muzic-16d63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqbL6QAVoG4ApgcziPkltE6jFMgjCwYp0',
    appId: '1:139054927656:ios:c10470e6885c67d1c74a1d',
    messagingSenderId: '139054927656',
    projectId: 'muzic-16d63',
    storageBucket: 'muzic-16d63.appspot.com',
    iosBundleId: 'com.example.muzicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqbL6QAVoG4ApgcziPkltE6jFMgjCwYp0',
    appId: '1:139054927656:ios:c10470e6885c67d1c74a1d',
    messagingSenderId: '139054927656',
    projectId: 'muzic-16d63',
    storageBucket: 'muzic-16d63.appspot.com',
    iosBundleId: 'com.example.muzicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD9M0KZpKzlGSfyQdzk8mU_CnxDJq3RWY',
    appId: '1:139054927656:web:328aca789cd1ae2ac74a1d',
    messagingSenderId: '139054927656',
    projectId: 'muzic-16d63',
    authDomain: 'muzic-16d63.firebaseapp.com',
    storageBucket: 'muzic-16d63.appspot.com',
    measurementId: 'G-9SL8JZEMN5',
  );
}
